import type { Shortcut } from '../types';

export const DEFAULT_SHORTCUTS: Record<string, Shortcut> = {
	toggleSidebar: {
		id: 'toggleSidebar',
		label: 'Toggle Sidebar',
		keys: ['Meta', 'b'],
		description: 'Show or hide the left sidebar',
		category: 'Layout',
	},
	toggleRightPanel: {
		id: 'toggleRightPanel',
		label: 'Toggle Right Panel',
		keys: ['Meta', 'Shift', 'b'],
		description: 'Show or hide the right panel',
		category: 'Layout',
	},
	cyclePrev: {
		id: 'cyclePrev',
		label: 'Previous Project',
		keys: ['Meta', '['],
		description: 'Switch to the previous project in the sidebar',
		category: 'Navigation',
	},
	cycleNext: {
		id: 'cycleNext',
		label: 'Next Project',
		keys: ['Meta', ']'],
		description: 'Switch to the next project in the sidebar',
		category: 'Navigation',
	},
	navBack: {
		id: 'navBack',
		label: 'Navigate Back',
		keys: ['Meta', 'Shift', ','],
		description: 'Go back through navigation history',
		category: 'Navigation',
	},
	navForward: {
		id: 'navForward',
		label: 'Navigate Forward',
		keys: ['Meta', 'Shift', '.'],
		description: 'Go forward through navigation history',
		category: 'Navigation',
	},
	newInstance: {
		id: 'newInstance',
		label: 'New',
		keys: ['Meta', 'n'],
		description: 'Create a new project or worktree',
		category: 'Projects',
	},
	killInstance: {
		id: 'killInstance',
		label: 'Remove',
		keys: ['Meta', 'Shift', 'Backspace'],
		description: 'Remove the active project',
		category: 'Projects',
	},
	toggleMode: {
		id: 'toggleMode',
		label: 'Focus Persistent Terminal',
		keys: ['Meta', 'j'],
		description: 'Switch between AI and terminal modes',
		category: 'Terminal',
	},
	clearContext: {
		id: 'clearContext',
		label: 'Clear Context',
		keys: ['Meta', 'k'],
		description: 'Clear the current conversation context',
		category: 'Terminal',
	},
	quickAction: {
		id: 'quickAction',
		label: 'Quick Actions',
		keys: ['Meta', 'Shift', 'p'],
		description: 'Open the command palette',
		category: 'Utility',
	},
	settings: {
		id: 'settings',
		label: 'Open Settings',
		keys: ['Meta', ','],
		description: 'Open the settings panel',
		category: 'Utility',
	},
	agentSettings: {
		id: 'agentSettings',
		label: 'Open Project Settings',
		keys: ['Alt', 'Meta', ','],
		description: 'Open settings for the active project',
		category: 'Projects',
	},
	goToFiles: {
		id: 'goToFiles',
		label: 'Go to Files Tab',
		keys: ['Meta', 'Shift', 'e'],
		description: 'Open the file explorer in the right panel',
		category: 'Files & Git',
	},
	goToHistory: {
		id: 'goToHistory',
		label: 'Go to History Tab',
		keys: ['Meta', 'Shift', 'h'],
		description: 'Open the history tab in the right panel',
		category: 'Files & Git',
	},
	toggleMarkdownMode: {
		id: 'toggleMarkdownMode',
		label: 'Toggle Edit/Preview',
		keys: ['Meta', 'e'],
		description: 'Toggle between rendered and raw markdown in chat',
		category: 'Files & Git',
	},
	focusInput: {
		id: 'focusInput',
		label: 'Toggle Input/Output Focus',
		keys: ['Meta', '.'],
		description: 'Switch focus between the input field and output area',
		category: 'Navigation',
	},
	focusSidebar: {
		id: 'focusSidebar',
		label: 'Focus Sidebar',
		keys: ['Meta', 'Shift', 'a'],
		description: 'Move keyboard focus to the sidebar',
		category: 'Navigation',
	},
	viewGitDiff: {
		id: 'viewGitDiff',
		label: 'View Git Diff',
		keys: ['Meta', 'Shift', 'd'],
		description: 'Show uncommitted changes as a diff',
		category: 'Files & Git',
	},
	viewGitLog: {
		id: 'viewGitLog',
		label: 'View Git Log',
		keys: ['Meta', 'Shift', 'g'],
		description: 'Open the git commit log',
		category: 'Files & Git',
	},
	agentSessions: {
		id: 'agentSessions',
		label: 'View Project History',
		keys: ['Meta', 'Shift', 'l'],
		description: 'Browse saved conversation sessions for this project',
		category: 'Projects',
	},
	systemLogs: {
		id: 'systemLogs',
		label: 'System Log Viewer',
		keys: ['Alt', 'Meta', 'l'],
		description: 'Open the system log viewer',
		category: 'Utility',
	},
	processMonitor: {
		id: 'processMonitor',
		label: 'System Process Monitor',
		keys: ['Alt', 'Meta', 'p'],
		description: 'Open the process monitor',
		category: 'Utility',
	},
	jumpToBottom: {
		id: 'jumpToBottom',
		label: 'Jump to Bottom',
		keys: ['Meta', 'Shift', 'j'],
		description: 'Scroll the output area to the latest content',
		category: 'Navigation',
	},
	fuzzyFileSearch: {
		id: 'fuzzyFileSearch',
		label: 'Fuzzy File Search',
		keys: ['Meta', 'p'],
		description: 'Quick open a file by name',
		category: 'Files & Git',
	},
	toggleAutoScroll: {
		id: 'toggleAutoScroll',
		label: 'Toggle Auto-Scroll AI Output',
		keys: ['Alt', 'Meta', 's'],
		description: 'Enable or disable automatic scrolling of AI output',
		category: 'Utility',
	},
	usagePanel: {
		id: 'usagePanel',
		label: 'Usage Panel',
		keys: ['Alt', 'Meta', 'u'],
		description: 'Open the API usage panel',
		category: 'Utility',
	},
};

// Non-editable shortcuts (displayed in help but not configurable)
export const FIXED_SHORTCUTS: Record<string, Shortcut> = {
	jumpToSession: {
		id: 'jumpToSession',
		label: 'Jump to Project (1-9, 0=10th)',
		keys: ['Alt', 'Meta', '1-0'],
		description: 'Jump directly to a project by its position number',
		category: 'Navigation',
	},
	filterFiles: {
		id: 'filterFiles',
		label: 'Filter Files (in Files tab)',
		keys: ['Meta', 'f'],
		description: 'Filter the file tree when the Files tab is focused',
		category: 'Files & Git',
	},
	filterSessions: {
		id: 'filterSessions',
		label: 'Filter Projects (in Sidebar)',
		keys: ['Meta', 'f'],
		description: 'Filter the project list when the sidebar is focused',
		category: 'Navigation',
	},
	filterHistory: {
		id: 'filterHistory',
		label: 'Filter History (in History tab)',
		keys: ['Meta', 'f'],
		description: 'Filter the history list when the History tab is focused',
		category: 'Files & Git',
	},
	searchLogs: {
		id: 'searchLogs',
		label: 'Search System Logs',
		keys: ['Meta', 'f'],
		description: 'Search within the system log viewer',
		category: 'Utility',
	},
	searchOutput: {
		id: 'searchOutput',
		label: 'Search Output (in Main Window)',
		keys: ['Meta', 'f'],
		description: 'Search within the main output area',
		category: 'Utility',
	},
	filePreviewBack: {
		id: 'filePreviewBack',
		label: 'File Preview: Go Back',
		keys: ['Meta', 'ArrowLeft'],
		description: 'Navigate back in file preview history',
		category: 'Files & Git',
	},
	filePreviewForward: {
		id: 'filePreviewForward',
		label: 'File Preview: Go Forward',
		keys: ['Meta', 'ArrowRight'],
		description: 'Navigate forward in file preview history',
		category: 'Files & Git',
	},
};

// Tab navigation shortcuts (AI mode only)
export const TAB_SHORTCUTS: Record<string, Shortcut> = {
	tabSwitcher: {
		id: 'tabSwitcher',
		label: 'Tab Switcher',
		keys: ['Alt', 'Meta', 't'],
		description: 'Open the tab switcher overlay',
		category: 'Tabs',
	},
	newTab: {
		id: 'newTab',
		label: 'New Tab',
		keys: ['Meta', 't'],
		description: 'Create a new AI conversation tab',
		category: 'Tabs',
	},
	closeTab: {
		id: 'closeTab',
		label: 'Close Tab',
		keys: ['Meta', 'w'],
		description: 'Close the active tab',
		category: 'Tabs',
	},
	reopenClosedTab: {
		id: 'reopenClosedTab',
		label: 'Reopen Closed Tab',
		keys: ['Meta', 'Shift', 't'],
		description: 'Restore the most recently closed tab',
		category: 'Tabs',
	},
	renameTab: {
		id: 'renameTab',
		label: 'Rename Tab',
		keys: ['Meta', 'Shift', 'r'],
		description: 'Rename the active tab',
		category: 'Tabs',
	},
	toggleShowThinking: {
		id: 'toggleShowThinking',
		label: 'Toggle Show Thinking',
		keys: ['Meta', 'Shift', 'k'],
		description: 'Cycle thinking display mode: off, on, or sticky',
		category: 'Tabs',
	},
	prevTab: {
		id: 'prevTab',
		label: 'Previous Tab',
		keys: ['Meta', 'Shift', '['],
		description: 'Switch to the previous tab',
		category: 'Tabs',
	},
	nextTab: {
		id: 'nextTab',
		label: 'Next Tab',
		keys: ['Meta', 'Shift', ']'],
		description: 'Switch to the next tab',
		category: 'Tabs',
	},
	goToTab1: {
		id: 'goToTab1',
		label: 'Go to Tab 1',
		keys: ['Meta', '1'],
		description: 'Jump to the first tab',
		category: 'Tabs',
	},
	goToTab2: {
		id: 'goToTab2',
		label: 'Go to Tab 2',
		keys: ['Meta', '2'],
		description: 'Jump to the second tab',
		category: 'Tabs',
	},
	goToTab3: {
		id: 'goToTab3',
		label: 'Go to Tab 3',
		keys: ['Meta', '3'],
		description: 'Jump to the third tab',
		category: 'Tabs',
	},
	goToTab4: {
		id: 'goToTab4',
		label: 'Go to Tab 4',
		keys: ['Meta', '4'],
		description: 'Jump to the fourth tab',
		category: 'Tabs',
	},
	goToTab5: {
		id: 'goToTab5',
		label: 'Go to Tab 5',
		keys: ['Meta', '5'],
		description: 'Jump to the fifth tab',
		category: 'Tabs',
	},
	goToTab6: {
		id: 'goToTab6',
		label: 'Go to Tab 6',
		keys: ['Meta', '6'],
		description: 'Jump to the sixth tab',
		category: 'Tabs',
	},
	goToTab7: {
		id: 'goToTab7',
		label: 'Go to Tab 7',
		keys: ['Meta', '7'],
		description: 'Jump to the seventh tab',
		category: 'Tabs',
	},
	goToTab8: {
		id: 'goToTab8',
		label: 'Go to Tab 8',
		keys: ['Meta', '8'],
		description: 'Jump to the eighth tab',
		category: 'Tabs',
	},
	goToTab9: {
		id: 'goToTab9',
		label: 'Go to Tab 9',
		keys: ['Meta', '9'],
		description: 'Jump to the ninth tab',
		category: 'Tabs',
	},
	goToLastTab: {
		id: 'goToLastTab',
		label: 'Go to Last Tab',
		keys: ['Meta', '0'],
		description: 'Jump to the last tab',
		category: 'Tabs',
	},
};
